vim.cmd.hi 'Normal guisp=NONE guifg=#CDD6F4 guibg=#1E1E2E gui=NONE cterm=NONE'
vim.cmd.hi 'Visual guisp=NONE guifg=NONE guibg=#45475A gui=bold cterm=bold'
vim.cmd.hi 'Conceal guisp=NONE guifg=#7F849C guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'ColorColumn guisp=NONE guifg=NONE guibg=#313244 gui=NONE cterm=NONE'
vim.cmd.hi 'Cursor guisp=NONE guifg=#1E1E2E guibg=#F5E0DC gui=NONE cterm=NONE'
vim.cmd.hi 'lCursor guisp=NONE guifg=#1E1E2E guibg=#F5E0DC gui=NONE cterm=NONE'
vim.cmd.hi 'CursorIM guisp=NONE guifg=#1E1E2E guibg=#F5E0DC gui=NONE cterm=NONE'
vim.cmd.hi 'CursorColumn guisp=NONE guifg=NONE guibg=#181825 gui=NONE cterm=NONE'
vim.cmd.hi 'CursorLine guisp=NONE guifg=NONE guibg=#313244 gui=NONE cterm=NONE'
vim.cmd.hi 'Directory guisp=NONE guifg=#89B4FA guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'DiffAdd guisp=NONE guifg=#1E1E2E guibg=#A6E3A1 gui=NONE cterm=NONE'
vim.cmd.hi 'DiffChange guisp=NONE guifg=#1E1E2E guibg=#F9E2AF gui=NONE cterm=NONE'
vim.cmd.hi 'DiffDelete guisp=NONE guifg=#1E1E2E guibg=#F38BA8 gui=NONE cterm=NONE'
vim.cmd.hi 'DiffText guisp=NONE guifg=#1E1E2E guibg=#89B4FA gui=NONE cterm=NONE'
vim.cmd.hi 'EndOfBuffer guisp=NONE guifg=NONE guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'ErrorMsg guisp=NONE guifg=#F38BA8 guibg=NONE gui=bolditalic cterm=bold,italic'
vim.cmd.hi 'VertSplit guisp=NONE guifg=#11111B guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Folded guisp=NONE guifg=#89B4FA guibg=#45475A gui=NONE cterm=NONE'
vim.cmd.hi 'FoldColumn guisp=NONE guifg=#6C7086 guibg=#1E1E2E gui=NONE cterm=NONE'
vim.cmd.hi 'SignColumn guisp=NONE guifg=#45475A guibg=#1E1E2E gui=NONE cterm=NONE'
vim.cmd.hi 'IncSearch guisp=NONE guifg=#45475A guibg=#F5C2E7 gui=NONE cterm=NONE'
vim.cmd.hi 'CursorLineNR guisp=NONE guifg=#B4BEFE guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'LineNr guisp=NONE guifg=#45475A guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'MatchParen guisp=NONE guifg=#FAB387 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'ModeMsg guisp=NONE guifg=#CDD6F4 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'MoreMsg guisp=NONE guifg=#89B4FA guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'NonText guisp=NONE guifg=#6C7086 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Pmenu guisp=NONE guifg=#9399B2 guibg=#313244 gui=NONE cterm=NONE'
vim.cmd.hi 'PmenuSel guisp=NONE guifg=#CDD6F4 guibg=#45475A gui=bold cterm=bold'
vim.cmd.hi 'PmenuSbar guisp=NONE guifg=NONE guibg=#45475A gui=NONE cterm=NONE'
vim.cmd.hi 'PmenuThumb guisp=NONE guifg=NONE guibg=#6C7086 gui=NONE cterm=NONE'
vim.cmd.hi 'Question guisp=NONE guifg=#89B4FA guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'QuickFixLine guisp=NONE guifg=NONE guibg=#45475A gui=bold cterm=bold'
vim.cmd.hi 'Search guisp=NONE guifg=#F5C2E7 guibg=#45475A gui=bold cterm=bold'
vim.cmd.hi 'SpecialKey guisp=NONE guifg=#A6ADC8 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'SpellBad guisp=NONE guifg=#1E1E2E guibg=#F38BA8 gui=NONE cterm=NONE'
vim.cmd.hi 'SpellCap guisp=NONE guifg=#1E1E2E guibg=#F9E2AF gui=NONE cterm=NONE'
vim.cmd.hi 'SpellLocal guisp=NONE guifg=#1E1E2E guibg=#89B4FA gui=NONE cterm=NONE'
vim.cmd.hi 'SpellRare guisp=NONE guifg=#1E1E2E guibg=#A6E3A1 gui=NONE cterm=NONE'
vim.cmd.hi 'StatusLine guisp=NONE guifg=#CDD6F4 guibg=#181825 gui=NONE cterm=NONE'
vim.cmd.hi 'StatusLineNC guisp=NONE guifg=#45475A guibg=#181825 gui=NONE cterm=NONE'
vim.cmd.hi 'StatusLineTerm guisp=NONE guifg=#CDD6F4 guibg=#181825 gui=NONE cterm=NONE'
vim.cmd.hi 'StatusLineTermNC guisp=NONE guifg=#45475A guibg=#181825 gui=NONE cterm=NONE'
vim.cmd.hi 'TabLine guisp=NONE guifg=#45475A guibg=#181825 gui=NONE cterm=NONE'
vim.cmd.hi 'TabLineFill guisp=NONE guifg=NONE guibg=#181825 gui=NONE cterm=NONE'
vim.cmd.hi 'TabLineSel guisp=NONE guifg=#A6E3A1 guibg=#45475A gui=NONE cterm=NONE'
vim.cmd.hi 'Title guisp=NONE guifg=#89B4FA guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'VisualNOS guisp=NONE guifg=NONE guibg=#45475A gui=bold cterm=bold'
vim.cmd.hi 'WarningMsg guisp=NONE guifg=#F9E2AF guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'WildMenu guisp=NONE guifg=NONE guibg=#6C7086 gui=NONE cterm=NONE'
vim.cmd.hi 'Comment guisp=NONE guifg=#6C7086 guibg=NONE gui=italic cterm=italic'
vim.cmd.hi 'Constant guisp=NONE guifg=#FAB387 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'Identifier guisp=NONE guifg=#F2CDCD guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Statement guisp=NONE guifg=#CBA6F7 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'PreProc guisp=NONE guifg=#F5C2E7 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Type guisp=NONE guifg=#89B4FA guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Special guisp=NONE guifg=#F5C2E7 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Underlined guisp=NONE guifg=#CDD6F4 guibg=#1E1E2E gui=underline cterm=underline'
vim.cmd.hi 'Error guisp=NONE guifg=#F38BA8 guibg=NONE gui=underline cterm=underline'
vim.cmd.hi 'Todo guisp=NONE guifg=#1E1E2E guibg=#F2CDCD gui=bold cterm=bold'

vim.cmd.hi 'String guisp=NONE guifg=#A6E3A1 guibg=NONE gui=italic cterm=italic'
vim.cmd.hi 'Character guisp=NONE guifg=#94E2D5 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'Number guisp=NONE guifg=#FAB387 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'Boolean guisp=NONE guifg=#FAB387 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'Float guisp=NONE guifg=#FAB387 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Function guisp=NONE guifg=#89B4FA guibg=NONE gui=italic cterm=italic'
vim.cmd.hi 'Conditional guisp=NONE guifg=#F38BA8 guibg=NONE gui=bolditalic cterm=bold,italic'
vim.cmd.hi 'Repeat guisp=NONE guifg=#F38BA8 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'Label guisp=NONE guifg=#FAB387 guibg=NONE gui=bold cterm=bold'
vim.cmd.hi 'Operator guisp=NONE guifg=#89DCEB guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Keyword guisp=NONE guifg=#F5C2E7 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Include guisp=NONE guifg=#F5C2E7 guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'StorageClass guisp=NONE guifg=#F9E2AF guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Structure guisp=NONE guifg=#F9E2AF guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'Typedef guisp=NONE guifg=#F9E2AF guibg=NONE gui=NONE cterm=NONE'
vim.cmd.hi 'debugPC guisp=NONE guifg=NONE guibg=#11111B gui=NONE cterm=NONE'
vim.cmd.hi 'debugBreakpoint guisp=NONE guifg=#6C7086 guibg=#1E1E2E gui=NONE cterm=NONE'


-- PLUGINS

-- blink.indent
vim.cmd.hi 'BlinkIndent guifg=#313244'
vim.cmd.hi 'BlinkIndentScope guifg=#9399B2'

-- blink.cmp (icons)
vim.cmd.hi 'BlinkCmpKindText guifg=#A6E3A1'
vim.cmd.hi 'BlinkCmpKindMethod guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindFunction guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindConstructor guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindField guifg=#A6E3A1'
vim.cmd.hi 'BlinkCmpKindVariable guifg=#F2CDCD'
vim.cmd.hi 'BlinkCmpKindClass guifg=#F9E2Af'
vim.cmd.hi 'BlinkCmpKindInterface guifg=#F9E2Af'
vim.cmd.hi 'BlinkCmpKindModule guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindProperty guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindUnit guifg=#A6E3A1'
vim.cmd.hi 'BlinkCmpKindValue guifg=#FAB387'
vim.cmd.hi 'BlinkCmpKindEnum guifg=#F9E2Af'
vim.cmd.hi 'BlinkCmpKindKeyword guifg=#CBA6F7'
vim.cmd.hi 'BlinkCmpKindSnippet guifg=#F2CDCD'
vim.cmd.hi 'BlinkCmpKindColor guifg=#F38BA8'
vim.cmd.hi 'BlinkCmpKindFile guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindReference guifg=#F38BA8'
vim.cmd.hi 'BlinkCmpKindFolder guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindEnumMember guifg=#94e2d5'
vim.cmd.hi 'BlinkCmpKindConstant guifg=#FAB387'
vim.cmd.hi 'BlinkCmpKindStruct guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindEvent guifg=#89B4FA'
vim.cmd.hi 'BlinkCmpKindOperator guifg=#89DCEB'
vim.cmd.hi 'BlinkCmpKindTypeParameter guifg=#EBA0AC'
vim.cmd.hi 'BlinkCmpKindCopilot guifg=#94E2D5'

-- mini diff

vim.cmd.hi 'MiniDiffSignAdd guifg=#A6E3A1'
vim.cmd.hi 'MiniDiffSignChange guifg=#F9E2AF'
vim.cmd.hi 'MiniDiffSignDelete guifg=#F38BA8'
vim.cmd.hi 'link MiniDiffOverAdd DiffAdd'
vim.cmd.hi 'link MiniDiffOverChange DiffText'
vim.cmd.hi 'link MiniDiffOverContext DiffChange'
vim.cmd.hi 'link MiniDiffOverDelete DiffDelete'
